# Generated by Django 6.1 on 2026-09-14 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_education'),
    ]

    operations = [
        migrations.AddField(
            model_name='education',
            name='skills',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
