# Generated by Django 6.1 on 2026-09-14 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_education_skills'),
    ]

    operations = [
        migrations.AddField(
            model_name='experience',
            name='stage',
            field=models.CharField(choices=[('university', 'University'), ('high-school', 'High School')], default='university', max_length=20),
        ),
    ]
