# Generated by Django 6.1 on 2026-09-20 23:40

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_alter_experience_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='Competition',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('organizer', models.CharField(max_length=255)),
                ('competition_type', models.CharField(choices=[('hackathon', 'Hackathon'), ('data competition', 'Data Competition'), ('ui/ux', 'UI/UX')], max_length=30)),
                ('description', models.TextField()),
                ('competition_date', models.DateField()),
                ('achievement', models.CharField(max_length=255)),
                ('is_team', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('project_url', models.URLField(blank=True)),
                ('project_image_url', models.URLField(blank=True, max_length=500)),
            ],
        ),
    ]
