# Generated by Django 6.1 on 2026-09-21 04:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_competition'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='competition',
            name='is_team',
        ),
        migrations.AddField(
            model_name='competition',
            name='participation_type',
            field=models.CharField(choices=[('individual', 'Individual'), ('group', 'Group')], default='individual', max_length=10),
        ),
    ]
